Repository ispp-yourney/angular-app, pull requests merged in 2021-04, with the labels that each got.

#42 Corregido error en el despliegue
  .travis.yml
  server.js
  src/app/app-routing.module.ts
  src/app/app.module.ts
  src/app/components/itinerary/itineraryshow/itineraryview.component.ts
  src/app/components/itinerary/my-itineraries/my-itineraries.component.css
  src/app/components/itinerary/my-itineraries/my-itineraries.component.html
  src/app/components/itinerary/my-itineraries/my-itineraries.component.ts
Labels: enhancement

#43 #15 Se añade la funcionalidad de creación de itinerarios
  angular.json
  src/app/app-routing.module.ts
  src/app/app.module.ts
  src/app/components/itinerary/itineraryform/itineraryform.component.css
  src/app/components/itinerary/itineraryform/itineraryform.component.html
  src/app/components/itinerary/itineraryform/itineraryform.component.ts
  src/app/components/itinerary/itineraryupdate/itineraryupdate.component.css
  src/app/components/itinerary/itineraryupdate/itineraryupdate.component.html
  src/app/components/itinerary/itineraryupdate/itineraryupdate.component.ts
  src/app/models/itinerary.ts
  src/app/services/activity.service.ts
  src/app/services/itinerary.service.ts
  src/scripts/itinerary.js
Labels: enhancement

#44 Funcionalidad completa de creación y modificación de itinerarios #15
  src/app/app-routing.module.ts
  src/app/components/itinerary/itineraryform/itineraryform.component.html
  src/app/components/itinerary/itineraryform/itineraryform.component.ts
  src/app/components/itinerary/itineraryshow/itineraryview.component.html
  src/app/components/itinerary/itineraryupdate/itineraryupdate.component.css
  src/app/components/itinerary/itineraryupdate/itineraryupdate.component.html
  src/app/components/itinerary/itineraryupdate/itineraryupdate.component.ts
  src/app/components/menu/menu.component.ts
  src/app/components/profile/profile.component.html
  src/app/components/profile/profile.component.ts
  src/app/models/itinerary.ts
  src/app/services/activity.service.ts
  src/app/services/auth.service.ts
  src/app/services/itinerary.service.ts
  src/app/services/landmark.service.ts
Labels: enhancement

#45 Feature 12.4: Creación de Filtros para la busqueda de itinerarios.
  src/app/app-routing.module.ts
  src/app/components/buscador/buscador.component.css
  src/app/components/buscador/buscador.component.html
  src/app/components/buscador/buscador.component.ts
  src/app/components/itinerary/itineraryupdate/itineraryupdate.component.ts
  src/app/components/menu/menu.component.html
  src/app/components/menu/menu.component.ts
  src/app/components/operations/login/login.component.ts
  src/app/components/profile/profile.component.html
  src/app/services/buscador.service.ts
Labels: enhancement

#55 Implementado listado de comentarios
  src/app/app.module.ts
  src/app/components/comment/commentform/commentform.component.css
  src/app/components/comment/commentform/commentform.component.html
  src/app/components/comment/commentform/commentform.component.ts
  src/app/components/itinerary/itineraryshow/itineraryview.component.css
  src/app/components/itinerary/itineraryshow/itineraryview.component.html
  src/app/components/itinerary/itineraryshow/itineraryview.component.ts
  src/app/components/menu/menu.component.css
  src/app/models/comment.ts
  src/app/models/itinerary.ts
  src/app/services/itinerary.service.ts
  src/db.json
  src/styles.css
Labels: enhancement

#56 Feature issue#54
  e2e/src/0login.e2e-spec.ts
  package-lock.json
  package.json
  src/app/app.module.ts
  src/app/components/comment/commentform/commentform.component.css
  src/app/components/comment/commentform/commentform.component.html
  src/app/components/comment/commentform/commentform.component.ts
  src/app/components/index/index.component.css
  src/app/components/index/index.component.html
  src/app/components/itinerary/itineraryform/itineraryform.component.html
  src/app/components/itinerary/itineraryshow/itineraryview.component.css
  src/app/components/itinerary/itineraryshow/itineraryview.component.html
  src/app/components/menu/menu.component.css
  src/app/components/operations/login/login.component.css
  src/app/components/operations/login/login.component.html
  src/app/components/operations/register/register.component.css
  src/app/components/operations/register/register.component.html
  src/app/models/comment.ts
  src/app/models/itinerary.ts
  src/app/services/comment.service.ts
  src/index.html
  src/styles.css
Labels: enhancement

#62 Feature issue#59
  src/app/components/itinerary/itineraryform/itineraryform.component.html
  src/app/components/itinerary/itineraryform/itineraryform.component.ts
  src/app/components/itinerary/itineraryupdate/itineraryupdate.component.html
  src/app/components/itinerary/itineraryupdate/itineraryupdate.component.ts
  src/app/components/profile/profile.component.css
  src/app/components/profile/profile.component.html
  src/app/components/profile/profile.component.ts
  src/app/models/itinerary.ts
  src/app/services/image.service.ts
Labels: enhancement

#63 Edicion de usuarios
  package-lock.json
  src/app/components/operations/register/register.component.html
  src/app/components/profile/profile.component.css
  src/app/components/profile/profile.component.html
  src/app/components/profile/profile.component.ts
  src/app/services/auth.service.ts
Labels: enhancement

#65 Patrón de contraseña ajustado
  src/app/components/operations/register/register.component.html
Labels: bug

#70 Añadir info.yml
  info.yml
Labels: auditory

#74 Feature issue#68
  src/app/components/buscador-landmark/buscador-landmark.component.css
  src/app/components/buscador-landmark/buscador-landmark.component.html
  src/app/components/buscador-landmark/buscador-landmark.component.ts
  src/app/components/buscador/buscador.component.css
  src/app/components/buscador/buscador.component.html
  src/app/components/comment/commentform/commentform.component.html
  src/app/components/itinerary/itinerarylist/itinerarylist.component.css
  src/app/components/itinerary/itinerarylist/itinerarylist.component.html
  src/app/components/itinerary/itinerarylist/itinerarylist.component.ts
  src/app/components/menu/menu.component.html
  src/app/components/profile/profile.component.css
  src/app/components/profile/profile.component.html
  src/app/services/itinerary.service.ts
Labels: enhancement

#75 Implementación compartir punto de interés
  src/app/components/buscador-landmark/buscador-landmark.component.css
  src/app/components/buscador-landmark/buscador-landmark.component.html
  src/app/components/buscador-landmark/buscador-landmark.component.ts
  src/app/components/buscador/buscador.component.html
  src/app/components/buscador/buscador.component.ts
  src/app/components/itinerary/itineraryform/itineraryform.component.css
  src/app/components/itinerary/itineraryform/itineraryform.component.html
  src/app/components/itinerary/itineraryform/itineraryform.component.ts
  src/app/components/itinerary/itineraryupdate/itineraryupdate.component.html
  src/app/components/itinerary/itineraryupdate/itineraryupdate.component.ts
  src/app/components/landmark/landmark-show/landmark-show.component.html
  src/app/components/landmark/landmark-show/landmark-show.component.ts
Labels: enhancement

#77 Corrección de elementos de diseño
  src/app/components/buscador-landmark/buscador-landmark.component.css
  src/app/components/buscador-landmark/buscador-landmark.component.html
  src/app/components/buscador/buscador.component.css
  src/app/components/buscador/buscador.component.html
  src/app/components/buscador/buscador.component.ts
  src/app/components/index/index.component.css
  src/app/components/index/index.component.html
  src/app/components/itinerary/itineraryform/itineraryform.component.css
  src/app/components/itinerary/itinerarylist/itinerarylist.component.css
  src/app/components/itinerary/itinerarylist/itinerarylist.component.html
  src/app/components/itinerary/itinerarylist/itinerarylist.component.ts
  src/app/components/itinerary/itineraryshow/itineraryview.component.ts
  src/app/services/buscador-landmark.service.ts
  src/app/services/buscador.service.ts
  src/styles.css
Labels: enhancement

#81 Corrección bug visual en compartir landmarks
  src/app/components/itinerary/itineraryform/itineraryform.component.html
  src/app/components/itinerary/itineraryform/itineraryform.component.ts
Labels: enhancement

#79 Corrección de errores de Governify
  info.yml
Labels: bug

#84 Feature Issue#82
  .travis.yml
  package-lock.json
  src/app/components/itinerary/itineraryform/itineraryform.component.html
  src/app/components/itinerary/itineraryform/itineraryform.component.ts
Labels: bug

#87 Se ha cambiado la propiedad categoria de un landmark a un select
  src/app/components/itinerary/itineraryform/itineraryform.component.html
Labels: bug

#88 Cambio en redirección al crear itinerario
  src/app/components/itinerary/itineraryform/itineraryform.component.ts
Labels: bug

#90 Pruebas de todos los servicios
  .gitignore
  .travis.yml
  angular.json
  karma.conf.js
  package-lock.json
  package.json
  sonar-project.properties
  src/app/components/landmark/landmark-create/landmark-create.component.ts
  src/app/models/comment.ts
  src/app/models/itinerary.ts
  src/app/services/activity.service.spec.ts
  src/app/services/activity.service.ts
  src/app/services/auth.service.spec.ts
  src/app/services/buscador-landmark.service.spec.ts
  src/app/services/buscador-landmark.service.ts
  src/app/services/buscador.service.spec.ts
  src/app/services/buscador.service.ts
  src/app/services/comment.service.spec.ts
  src/app/services/image.service.spec.ts
  src/app/services/itinerary.service.spec.ts
  src/app/services/itinerary.service.ts
  src/app/services/landmark.service.spec.ts
  src/app/services/landmark.service.ts
  src/app/services/token.service.spec.ts
  src/app/services/token.service.ts
Labels: testing

#91 Patrocinio de un punto de interés
  src/app/app.module.ts
  src/app/components/buscador-landmark/buscador-landmark.component.css
  src/app/components/buscador-landmark/buscador-landmark.component.ts
  src/app/components/buscador-results/buscador-results.component.ts
  src/app/components/buscador/buscador.component.css
  src/app/components/buscador/buscador.component.html
  src/app/components/buscador/buscador.component.ts
  src/app/components/here-map/here-map.component.ts
  src/app/components/itinerary/itineraryform/itineraryform.component.html
  src/app/components/itinerary/itineraryform/itineraryform.component.ts
  src/app/components/itinerary/itinerarylist/itinerarylist.component.ts
  src/app/components/itinerary/itineraryshow/itineraryview.component.css
  src/app/components/itinerary/itineraryshow/itineraryview.component.html
  src/app/components/itinerary/itineraryshow/itineraryview.component.ts
  src/app/components/itinerary/itineraryupdate/itineraryupdate.component.html
  src/app/components/itinerary/itineraryupdate/itineraryupdate.component.ts
  src/app/components/landmark/landmark-create/landmark-create.component.html
  src/app/components/landmark/landmark-create/landmark-create.component.ts
  src/app/components/landmark/landmark-show/landmark-show.component.css
  src/app/components/landmark/landmark-show/landmark-show.component.html
  src/app/components/landmark/landmark-show/landmark-show.component.ts
  src/app/components/menu/menu.component.html
  src/app/components/operations/login/login.component.html
  src/app/components/operations/login/login.component.ts
  src/app/components/operations/register/register.component.ts
  src/app/components/profile/profile.component.html
  src/app/components/profile/profile.component.ts
  src/app/models/itinerary.ts
  src/app/models/itineraryUserPage.ts
  src/app/models/search-filters.ts
  src/app/services/activity.service.ts
  src/app/services/auth.service.ts
  src/app/services/buscador-landmark.service.ts
  src/app/services/buscador.service.ts
  src/app/services/comment.service.ts
  src/app/services/itinerary.service.spec.ts
  src/app/services/itinerary.service.ts
  src/app/services/landmark.service.spec.ts
  src/app/services/landmark.service.ts
  src/assets/img/corona.png
Labels: bug, enhancement

#95 Se añade una selección entre los países del mundo
  src/app/components/itinerary/itineraryform/itineraryform.component.html
  src/app/components/itinerary/itineraryform/itineraryform.component.ts
  src/app/components/itinerary/itineraryupdate/itineraryupdate.component.html
  src/app/components/itinerary/itineraryupdate/itineraryupdate.component.ts
  src/app/components/landmark/landmark-create/landmark-create.component.html
  src/app/components/landmark/landmark-create/landmark-create.component.ts
  src/app/services/country.service.ts
Labels: enhancement

#93 Se indica la moneda en los formularios
  src/app/components/itinerary/itineraryform/itineraryform.component.html
  src/app/components/itinerary/itineraryupdate/itineraryupdate.component.html
  src/app/components/landmark/landmark-create/landmark-create.component.html
Labels: enhancement

#98 Corrección de errores e implementación de mejoras
  angular.json
  package-lock.json
  package.json
  src/app/app-routing.module.ts
  src/app/app.module.ts
  src/app/components/buscador-landmark/buscador-landmark.component.css
  src/app/components/buscador-landmark/buscador-landmark.component.html
  src/app/components/buscador-landmark/buscador-landmark.component.ts
  src/app/components/buscador/buscador.component.ts
  src/app/components/comment/commentform/commentform.component.ts
  src/app/components/itinerary/itineraryform/itineraryform.component.css
  src/app/components/itinerary/itineraryform/itineraryform.component.html
  src/app/components/itinerary/itineraryform/itineraryform.component.ts
  src/app/components/itinerary/itineraryshow/itineraryview.component.html
  src/app/components/itinerary/itineraryshow/itineraryview.component.ts
  src/app/components/itinerary/itineraryupdate/itineraryupdate.component.css
  src/app/components/itinerary/itineraryupdate/itineraryupdate.component.html
  src/app/components/itinerary/itineraryupdate/itineraryupdate.component.ts
  src/app/components/landmark/landmark-create/landmark-create.component.html
  src/app/components/landmark/landmark-create/landmark-create.component.ts
  src/app/components/operations/login/login.component.ts
  src/app/components/profile/profile.component.spec.ts
  src/app/components/profile/profile.component.ts
  src/app/services/activity.service.ts
  src/app/services/landmark.service.ts
  src/styles.css
Labels: bug, enhancement

#100 Admin puede modificar y editar datos
  src/app/components/comment/commentform/commentform.component.html
  src/app/components/comment/commentform/commentform.component.ts
  src/app/components/itinerary/itineraryshow/itineraryview.component.html
  src/app/components/itinerary/itineraryshow/itineraryview.component.ts
  src/app/components/itinerary/itineraryupdate/itineraryupdate.component.ts
  src/app/components/landmark/landmark-create/landmark-create.component.html
  src/app/components/landmark/landmark-create/landmark-create.component.ts
  src/app/components/landmark/landmark-show/landmark-show.component.html
  src/app/components/landmark/landmark-show/landmark-show.component.ts
  src/app/components/profile/profile.component.html
  src/app/services/landmark.service.ts
Labels: enhancement

#101 Correccion de errores y validaciones
  src/app/components/buscador-landmark/buscador-landmark.component.css
  src/app/components/buscador-landmark/buscador-landmark.component.html
  src/app/components/buscador/buscador.component.css
  src/app/components/buscador/buscador.component.html
  src/app/components/comment/commentform/commentform.component.html
  src/app/components/comment/commentform/commentform.component.ts
  src/app/components/itinerary/itineraryform/itineraryform.component.html
  src/app/components/itinerary/itineraryform/itineraryform.component.ts
  src/app/components/itinerary/itineraryupdate/itineraryupdate.component.html
  src/app/components/itinerary/itineraryupdate/itineraryupdate.component.ts
  src/app/components/landmark/landmark-create/landmark-create.component.html
  src/app/components/landmark/landmark-create/landmark-create.component.ts
  src/app/services/buscador.service.ts
Labels: enhancement

#103 Correccion de errores
  src/app/app.component.ts
  src/app/components/buscador-landmark/buscador-landmark.component.css
  src/app/components/buscador-landmark/buscador-landmark.component.ts
  src/app/components/buscador/buscador.component.css
  src/app/components/buscador/buscador.component.html
  src/app/components/buscador/buscador.component.ts
  src/app/components/comment/commentform/commentform.component.ts
  src/app/components/index/index.component.css
  src/app/components/itinerary/itineraryform/itineraryform.component.html
  src/app/components/itinerary/itineraryform/itineraryform.component.ts
  src/app/components/itinerary/itineraryshow/itineraryview.component.html
  src/app/components/itinerary/itineraryshow/itineraryview.component.ts
  src/app/components/itinerary/itineraryupdate/itineraryupdate.component.html
  src/app/components/itinerary/itineraryupdate/itineraryupdate.component.ts
  src/app/components/landmark/landmark-create/landmark-create.component.html
  src/app/components/landmark/landmark-create/landmark-create.component.ts
  src/app/components/landmark/landmark-show/landmark-show.component.html
  src/app/components/landmark/landmark-show/landmark-show.component.ts
  src/app/components/operations/login/login.component.html
  src/app/components/operations/login/login.component.ts
  src/app/components/operations/register/register.component.html
  src/app/components/operations/register/register.component.ts
  src/app/components/profile/profile.component.html
  src/app/components/profile/profile.component.ts
Labels: bug

#105 Feature issue#96: Tests de componentes
  angular.json
  e2e/src/0login.e2e-spec.ts
  e2e/src/1my-itineraries.e2e-spec.ts
  package-lock.json
  sonar-project.properties
  src/app/app-routing.module.ts
  src/app/components/comment/commentform/commentform.component.spec.ts
  src/app/components/comment/commentform/commentform.component.ts
  src/app/components/footer/footer.component.spec.ts
  src/app/components/index/index.component.html
  src/app/components/index/index.component.spec.ts
  src/app/components/index/index.component.ts
  src/app/components/itinerary/itineraryform/itineraryform.component.html
  src/app/components/itinerary/itineraryform/itineraryform.component.ts
  src/app/components/itinerary/itineraryupdate/itineraryupdate.component.ts
  src/app/components/landmark/landmark-create/landmark-create.component.spec.ts
  src/app/components/landmark/landmark-create/landmark-create.component.ts
  src/app/components/landmark/landmark-show/landmark-show.component.html
  src/app/components/landmark/landmark-show/landmark-show.component.spec.ts
  src/app/components/landmark/landmark-show/landmark-show.component.ts
  src/app/components/menu/menu.component.spec.ts
  src/app/components/menu/menu.component.ts
  src/app/components/not-found/not-found.component.spec.ts
  src/app/components/operations/login/login.component.spec.ts
  src/app/components/operations/login/login.component.ts
  src/app/components/operations/register/register.component.spec.ts
  src/app/components/operations/register/register.component.ts
  src/app/components/profile/profile.component.html
  src/app/components/profile/profile.component.spec.ts
  src/app/components/profile/profile.component.ts
  src/app/revisors/interceptor.service.spec.ts
  src/app/revisors/permissions.service.spec.ts
  src/app/services/activity.service.spec.ts
  src/app/services/country.service.spec.ts
  src/app/services/itinerary.service.spec.ts
  src/app/services/landmark.service.spec.ts
  src/app/services/landmark.service.ts
Labels: testing

#106 Corrección de errores
  src/app/app-routing.module.ts
  src/app/components/buscador-landmark/buscador-landmark.component.ts
  src/app/components/buscador/buscador.component.ts
  src/app/components/comment/commentform/commentform.component.html
  src/app/components/comment/commentform/commentform.component.ts
  src/app/components/itinerary/itineraryform/itineraryform.component.html
  src/app/components/itinerary/itineraryform/itineraryform.component.ts
  src/app/components/itinerary/itineraryshow/itineraryview.component.html
  src/app/components/itinerary/itineraryupdate/itineraryupdate.component.html
  src/app/components/itinerary/itineraryupdate/itineraryupdate.component.ts
  src/app/components/landmark/landmark-create/landmark-create.component.html
  src/app/components/landmark/landmark-create/landmark-create.component.spec.ts
  src/app/components/landmark/landmark-create/landmark-create.component.ts
  src/app/components/landmark/landmark-show/landmark-show.component.html
  src/app/components/landmark/landmark-show/landmark-show.component.spec.ts
  src/app/components/landmark/landmark-show/landmark-show.component.ts
  src/app/components/operations/register/register.component.html
  src/app/components/operations/register/register.component.ts
  src/app/components/profile/profile.component.html
  src/app/components/profile/profile.component.spec.ts
  src/app/components/profile/profile.component.ts
  src/app/revisors/interceptor.service.ts
Labels: bug

#108 Cambios previos a la entrega
  src/app/components/buscador-landmark/buscador-landmark.component.ts
  src/app/components/buscador/buscador.component.ts
  src/app/components/itinerary/itineraryform/itineraryform.component.ts
  src/app/components/itinerary/itineraryupdate/itineraryupdate.component.html
Labels: enhancement

#111 Actualización de url de backend
  src/environments/environment-ci.ts
Labels: configuration

#114 Modificada la vista de itinerario
  package-lock.json
  src/app/components/buscador/buscador.component.ts
  src/app/components/itinerary/itineraryshow/itineraryview.component.html
Labels: bug

#115 se ha añadido el simbolo de euro
  package-lock.json
  src/app/components/buscador/buscador.component.css
  src/app/components/buscador/buscador.component.html
Labels: enhancement

#118 Los nombres de los usuarios redirigen a su perfil
  src/app/components/comment/commentform/commentform.component.html
  src/app/components/itinerary/itineraryshow/itineraryview.component.html
Labels: enhancement

#119 Añadido botón para crear itinerarios
  src/app/components/buscador/buscador.component.html
  src/app/components/buscador/buscador.component.ts
Labels: enhancement

#124 Se mejora la interfaz de visualización del mapa
  src/app/components/here-map/here-map.component.ts
  src/index.html
Labels: enhancement

#125 Dashboard de administrador
  angular.json
  package-lock.json
  package.json
  src/app/app.module.ts
  src/app/components/dashboard/dashboard.component.css
  src/app/components/dashboard/dashboard.component.html
  src/app/components/dashboard/dashboard.component.ts
  src/app/components/profile/profile.component.html
  src/app/components/profile/profile.component.spec.ts
  src/app/components/profile/profile.component.ts
  src/app/services/dashboard.service.ts
Labels: enhancement

#127 Se añade Términos y Condiciones
  src/app/app-routing.module.ts
  src/app/app.module.ts
  src/app/components/menu/menu.component.html
  src/app/components/operations/register/register.component.html
  src/app/components/terms/terms.component.css
  src/app/components/terms/terms.component.html
  src/app/components/terms/terms.component.ts
Labels: enhancement

#129 Feature issue#121: Confirmación de cuenta
  package-lock.json
  package.json
  src/app/app-routing.module.ts
  src/app/app.module.ts
  src/app/components/buscador-landmark/buscador-landmark.component.css
  src/app/components/buscador-landmark/buscador-landmark.component.html
  src/app/components/buscador-landmark/buscador-landmark.component.spec.ts
  src/app/components/buscador-landmark/buscador-landmark.component.ts
  src/app/components/buscador/buscador.component.css
  src/app/components/buscador/buscador.component.html
  src/app/components/buscador/buscador.component.spec.ts
  src/app/components/buscador/buscador.component.ts
  src/app/components/confirmation-user/confirmation-user.component.css
  src/app/components/confirmation-user/confirmation-user.component.html
  src/app/components/confirmation-user/confirmation-user.component.spec.ts
  src/app/components/confirmation-user/confirmation-user.component.ts
  src/app/components/itinerary/itineraryform/itineraryform.component.html
  src/app/components/itinerary/itinerarylist/itinerarylist.component.html
  src/app/components/itinerary/itinerarylist/itinerarylist.component.spec.ts
  src/app/components/itinerary/itinerarylist/itinerarylist.component.ts
  src/app/components/itinerary/itineraryupdate/itineraryupdate.component.html
  src/app/components/operations/login/login.component.html
  src/app/components/operations/login/login.component.spec.ts
  src/app/components/operations/login/login.component.ts
  src/app/components/operations/register/register.component.html
  src/app/components/operations/register/register.component.spec.ts
  src/app/components/operations/register/register.component.ts
  src/app/components/profile/profile.component.html
  src/app/components/profile/profile.component.ts
  src/app/components/terms/terms.component.spec.ts
  src/app/models/itineraryUserPage.ts
  src/app/services/buscador.service.ts
  src/app/services/email-confirmation.service.spec.ts
  src/app/services/email-confirmation.service.ts
  src/app/services/itinerary.service.spec.ts
  src/app/services/itinerary.service.ts
  src/environments/environment-ci.ts
Labels: testing

#131 Feature-issue#130: Modificada url backend
  src/environments/environment-ci.ts
Labels: bug

#133 Correcciones de errores
  src/app/app-routing.module.ts
  src/app/components/itinerary/itineraryform/itineraryform.component.html
  src/app/components/itinerary/itineraryform/itineraryform.component.ts
  src/app/components/itinerary/itineraryshow/itineraryview.component.html
  src/app/components/landmark/landmark-create/landmark-create.component.html
  src/app/components/landmark/landmark-create/landmark-create.component.ts
  src/app/components/landmark/landmark-show/landmark-show.component.html
  src/app/components/landmark/landmark-show/landmark-show.component.ts
  src/app/components/profile/profile.component.html
Labels: bug

#135 Se añade el checkbox validando los términos y condiciones
  src/app/components/operations/register/register.component.html
  src/app/components/operations/register/register.component.ts
Labels: enhancement

#137 Feature issue#136: Correcciones y mejoras
  src/app/app-routing.module.ts
  src/app/components/buscador-landmark/buscador-landmark.component.css
  src/app/components/buscador-landmark/buscador-landmark.component.html
  src/app/components/buscador-landmark/buscador-landmark.component.ts
  src/app/components/buscador/buscador.component.css
  src/app/components/buscador/buscador.component.html
  src/app/components/buscador/buscador.component.spec.ts
  src/app/components/comment/commentform/commentform.component.css
  src/app/components/comment/commentform/commentform.component.html
  src/app/components/comment/commentform/commentform.component.ts
  src/app/components/footer/footer.component.css
  src/app/components/index/index.component.css
  src/app/components/index/index.component.html
  src/app/components/itinerary/itineraryform/itineraryform.component.css
  src/app/components/itinerary/itineraryform/itineraryform.component.html
  src/app/components/itinerary/itineraryform/itineraryform.component.spec.ts
  src/app/components/itinerary/itineraryform/itineraryform.component.ts
  src/app/components/itinerary/itineraryshow/itineraryview.component.css
  src/app/components/itinerary/itineraryshow/itineraryview.component.html
  src/app/components/itinerary/itineraryshow/itineraryview.component.ts
  src/app/components/itinerary/itineraryupdate/itineraryupdate.component.css
  src/app/components/itinerary/itineraryupdate/itineraryupdate.component.html
  src/app/components/itinerary/itineraryupdate/itineraryupdate.component.ts
  src/app/components/landmark/landmark-show/landmark-show.component.ts
  src/app/components/menu/menu.component.html
  src/app/components/operations/login/login.component.ts
  src/app/components/operations/register/register.component.ts
  src/app/components/profile/profile.component.html
  src/app/components/profile/profile.component.spec.ts
  src/assets/img/itineraryFeaturedLandmark.png
  src/assets/img/itineraryFeaturedUser.png
  src/styles.css
Labels: bug, enhancement

#139 Correcciones de la aplicacion
  src/app/components/comment/commentform/commentform.component.ts
  src/app/components/footer/footer.component.css
  src/app/components/index/index.component.css
  src/app/components/index/index.component.html
  src/app/components/itinerary/itineraryform/itineraryform.component.html
  src/app/components/itinerary/itineraryform/itineraryform.component.ts
  src/app/components/itinerary/itineraryshow/itineraryview.component.html
  src/app/components/itinerary/itineraryupdate/itineraryupdate.component.ts
  src/app/components/landmark/landmark-create/landmark-create.component.ts
  src/app/components/landmark/landmark-show/landmark-show.component.ts
Labels: bug
