Repository ispp-yourney/angular-app, pull requests merged in 2021-05, with the labels that each got.

#141 Feature issue#140: Corrección de errores tras testeo
  src/app/components/comment/commentform/commentform.component.css
  src/app/components/comment/commentform/commentform.component.html
  src/app/components/comment/commentform/commentform.component.ts
  src/app/components/itinerary/itineraryform/itineraryform.component.html
  src/app/components/itinerary/itineraryform/itineraryform.component.ts
  src/app/components/itinerary/itineraryupdate/itineraryupdate.component.ts
  src/app/components/landmark/landmark-create/landmark-create.component.ts
  src/app/components/landmark/landmark-show/landmark-show.component.ts
  src/app/components/operations/register/register.component.ts
  src/app/components/profile/profile.component.html
  src/app/components/profile/profile.component.ts
Labels: bug

#143 Se añade el uso de IP a los términos y condiciones
  src/app/components/terms/terms.component.html
Labels: enhancement

#145 Cambios en términos legales
  src/app/components/operations/register/register.component.html
  src/app/components/terms/terms.component.html
Labels: enhancement

#148 Actualización de url de backend
  src/environments/environment-ci.ts
Labels: configuration

#150 Añadida metaetiqueta de Google
  src/index.html
Labels: configuration

#152 Correción de cambios
  angular.json
  package-lock.json
  package.json
  src/app/app.component.ts
  src/app/components/index/index.component.css
  src/app/components/index/index.component.html
  src/app/components/itinerary/itineraryform/itineraryform.component.ts
  src/app/components/itinerary/itineraryupdate/itineraryupdate.component.ts
  src/app/components/landmark/landmark-create/landmark-create.component.ts
  src/app/components/operations/login/login.component.html
  src/app/components/operations/login/login.component.ts
  src/app/components/operations/register/register.component.html
  src/app/components/operations/register/register.component.ts
  src/app/components/profile/profile.component.ts
  src/app/components/terms/terms.component.html
  src/assets/img/avionpapel.png
  src/assets/img/itineraryFeaturedUser.png
  src/assets/img/new_logo.png
  src/assets/img/ruta_avion.png
  src/index.html
Labels: bug

#154 Cambios visuales
  src/app/components/comment/commentform/commentform.component.css
  src/app/components/comment/commentform/commentform.component.html
  src/app/components/index/index.component.html
  src/app/components/itinerary/itineraryshow/itineraryview.component.html
  src/app/components/operations/login/login.component.spec.ts
  src/app/components/operations/register/register.component.html
  src/app/components/operations/register/register.component.spec.ts
Labels: bug

#155 Puesta en producción de las funcionalidades de la fase Preparing Project Launch
  angular.json
  package-lock.json
  package.json
  src/app/app.component.ts
  src/app/components/comment/commentform/commentform.component.css
  src/app/components/comment/commentform/commentform.component.html
  src/app/components/index/index.component.css
  src/app/components/index/index.component.html
  src/app/components/itinerary/itineraryform/itineraryform.component.ts
  src/app/components/itinerary/itineraryshow/itineraryview.component.html
  src/app/components/itinerary/itineraryupdate/itineraryupdate.component.ts
  src/app/components/landmark/landmark-create/landmark-create.component.ts
  src/app/components/operations/login/login.component.html
  src/app/components/operations/login/login.component.spec.ts
  src/app/components/operations/login/login.component.ts
  src/app/components/operations/register/register.component.html
  src/app/components/operations/register/register.component.spec.ts
  src/app/components/operations/register/register.component.ts
  src/app/components/profile/profile.component.ts
  src/app/components/terms/terms.component.html
  src/assets/img/avionpapel.png
  src/assets/img/itineraryFeaturedUser.png
  src/assets/img/new_logo.png
  src/assets/img/ruta_avion.png
  src/index.html
Labels: bug, enhancement

#157 Actualización de url de backend
  src/environments/environment-ci.ts
Labels: configuration

#159 Corregido error en Legal
  src/app/components/itinerary/itineraryform/itineraryform.component.ts
  src/app/components/operations/register/register.component.html
  src/app/components/terms/terms.component.html
Labels: bug

#161 Corregido error de correo en Legal
  src/app/components/itinerary/itineraryform/itineraryform.component.ts
  src/app/components/operations/register/register.component.html
  src/app/components/terms/terms.component.html
Labels: bug

#163 Actualización de url de backend
  src/app/components/terms/terms.component.html
  src/environments/environment-ci.ts
Labels: configuration
